version: '3'

services:
  auth-ms:
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: agente47/auth-ms:latest
    environment:
      - PORT=3004
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - microservices_network
